### ISSUE TITLE
Deep Learning without using GPU is practically useless

### ISSUE THREAD

**Issue by xinkwang** [awslabs/ecs-deep-learning-workshop#3]
Can't understand why the tutorial does not cover how to use GPU (by changing the GPU in the tutorial script into CPU). Deep learning without using gpu is useless.

**Comment by schmutze** [comment]
Thanks for the note, @xinkwang. This content was used for a live workshop a few months back in a setting where it wasn't possible to secure a GPU for all attendees. We are working to update the material to demonstrate how to use a GPU for running MXNet on ECS as well.
