### ISSUE TITLE
Lab 1 step 2 it's not clear what to fill in after launching the cloudformation

### ISSUE THREAD

**Issue by garywu** [awslabs/ecs-deep-learning-workshop#4]
There are two screens after the initial screen:
Specify Details
Options

without entering values the stack creation failes:

13:07:52 UTC-0600	ROLLBACK_COMPLETE	AWS::CloudFormation::Stack	ecs-deep-learning-stack	
13:07:44 UTC-0600	ROLLBACK_IN_PROGRESS	AWS::CloudFormation::Stack	ecs-deep-learning-stack	Parameter validation failed: parameter value for parameter name KeyName does not exist. Rollback requested by user.
13:07:42 UTC-0600	CREATE_IN_PROGRESS	AWS::CloudFormation::Stack	ecs-deep-learning-stack	User Initiated

**Comment by garywu** [comment]
The above is due to not entering keypair. Lab 1 step 1 should mention to make sure to create the key pair in the zone Ohio (us-east-2)	
Oregon (us-west-2) to match cloudeformation link provided by zone 2. Otherwise the key pair would not be available in step 2.

**Comment by hub714** [comment]
I put in a screenshot that tells you to make sure you put in a keypair and also create it in the same region.

Thanks!
