### ISSUE TITLE
SpotFleet Should use WaitCondition

### ISSUE THREAD

**Issue by hub714** [awslabs/ecs-deep-learning-workshop#7]
Fairly sure this should work, so adding an issue to remember to do it.

**Comment by schmutze** [comment]
I added support for WaitCondition with the Spot Fleet in https://github.com/awslabs/ecs-deep-learning-workshop/commit/a1130f12022dbfe8925fc7a14e81ef85b0122369#diff-96d6df91321880abe9ab8c7ae902e783 but forgot to close this out.
